[package]
name = "harold-nfc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libgatekeeper-sys = "0.2.0"
gatekeeper-members = "0.1.0"
